steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/loutrerie-bot', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/loutrerie-bot']
  
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'loutrerie-bot'
    - '--image'
    - 'gcr.io/$PROJECT_ID/loutrerie-bot'
    - '--region'
    - 'europe-west1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-env-vars'
    - 'PORT=8080,DISCORD_TOKEN=MTQxMTc1MTA1MzY3Mzg4OTg3Mw.GaiE8a.GdLtzNirz8uLF4-nL7z-mNUWDmd1hr0raXdTtk'
    - '--cpu'
    - '1'
    - '--memory'
    - '512Mi'
    - '--min-instances'
    - '1'
    - '--max-instances'
    - '1'

options:
  logging: CLOUD_LOGGING_ONLY
